development:
  adapter: postgresql
  encoding: unicode
  database: photoboot_development
  pool: 5
  username: Juan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: photoboot_test
  pool: 5
  username: Juan
  password:
